/**
 * Codegen step — intentionally NOT part of tsup.
 *
 * tsup transpiles source files into output formats; it cannot execute the
 * resolved flat config and serialize the result. This script does exactly that:
 * it imports the built presets, runs them, harvests only their `rules`, drops
 * ESLint-9-only entries, and emits a static .eslintrc for ESLint 8 consumers.
 *
 * The emitted file references plugins by string name (not instances) so ESLint 8
 * resolves them from the consumer's own node_modules via peerDeps — which is why
 * we write a derived file here with fs/promises rather than letting tsup do it.
 *
 * Why not even tsup's `onSuccess` hook? With `dts: true`, `onSuccess` fires after
 * the JS build but races with the separate DTS worker and tsup's clean step: the
 * DTS phase wipes `dist` after assets are copied, so files written from the hook
 * get clobbered. Post-build steps must run strictly AFTER tsup exits — hence the
 * `tsup && node scripts/...` chain in package.json instead of an `onSuccess` hook.
 */
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PLUGIN_NAME } from '@kommo-crm/eslint-plugin';
import { base, typescript, react } from '../dist/index.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'dist/legacy.cjs');

/**
 * Plugins exposed to .eslintrc consumers. Each must be installed by the
 * consumer as a peerDependency (ESLint 8 resolves them from the project's
 * own node_modules, not from this package).
 */
const LEGACY_PLUGINS = [
  '@stylistic',
  '@typescript-eslint',
  'jsdoc',
  'prettier',
  'react',
  'react-hooks',
];

/**
 * Rules whose prefix starts with these strings are skipped:
 * - kommo/*: the package's custom rules are not exposed as a separate plugin
 *   for ESLint 8. Consumers must wire them manually via a local plugin if needed.
 * - react-you-might-not-need-an-effect/*: plugin requires the ESLint 9+ API.
 * - import/*: `import` is not in LEGACY_PLUGINS, and emitting rules for an
 *   undeclared plugin makes ESLint 8 abort at config load.
 */
const EXCLUDED_PREFIXES = [
  `${PLUGIN_NAME}/`,
  'react-you-might-not-need-an-effect/',
  'import/',
];

/**
 * Block whose `files` scoping is load-bearing. The legacy .eslintrc is emitted
 * as one flat `rules` object with no per-file scoping, so folding this block in
 * would fire its rules on every .js file a consumer owns. ESLint 8 consumers
 * simply do not get these rules.
 */
const TS_ONLY_BLOCK = '@kommo-crm/eslint-config/typescript/ts-only';

const collectRules = (configs) => {
  return Object.assign(
    {},
    ...configs
      .filter((config) => {
        return config?.name !== TS_ONLY_BLOCK;
      })
      .map((config) => {
        return config?.rules ?? {};
      })
  );
};

const allConfigs = [...base(), ...typescript(), ...react()];

const hasTsOnlyBlock = allConfigs.some((config) => {
  return config?.name === TS_ONLY_BLOCK;
});

if (!hasTsOnlyBlock) {
  throw new Error(
    `build-legacy: no config block named "${TS_ONLY_BLOCK}" — its TS-scoped rules would leak into the ESLint 8 output. Update TS_ONLY_BLOCK to match src/presets/typescript.ts.`
  );
}

const mergedRules = collectRules(allConfigs);

const rules = Object.fromEntries(
  Object.entries(mergedRules).filter(([key]) => {
    return !EXCLUDED_PREFIXES.some((prefix) => {
      return key.startsWith(prefix);
    });
  })
);

const body = `'use strict';

/**
 * Auto-generated legacy entry for ESLint 8 (.eslintrc). DO NOT EDIT by hand —
 * regenerated by scripts/build-legacy.mjs on every build.
 */
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2022,
    sourceType: 'module',
    ecmaFeatures: { jsx: true },
  },
  env: { browser: true, node: true, es2022: true },
  extends: ['eslint:recommended', 'plugin:prettier/recommended'],
  plugins: ${JSON.stringify(LEGACY_PLUGINS)},
  settings: { react: { version: 'detect' } },
  rules: ${JSON.stringify(rules, null, 2)},
};
`;

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, body);

console.log(`Wrote ${Object.keys(rules).length} rules → ${OUT}`);
